import { StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'rgba(39, 87, 158, 1)' },
  screen: { flex: 1, paddingHorizontal: 16, paddingTop: 8, backgroundColor: 'rgba(39, 87, 158, 1)' },
  
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#fff',
  },
  logo: {
    width: 210,
    height: 50,
  },
  logoutButton: {
    backgroundColor: '#2b2b31',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  logoutText: {
    color: '#d7d7dd',
    fontSize: 12,
    fontWeight: '600',
  },

  content: { flex: 1, gap: 12 },
  columns: { flexDirection: 'row' },
  rows: { flexDirection: 'column' },
  stack: { flexDirection: 'column' },
  left: { flex: 1 },
  right: { flex: 1 },
  top: { flex: 1 },
  bottom: { flex: 1 },

  section: {
    backgroundColor: '#121214',
    borderRadius: 16,
    paddingVertical: 8,
    overflow: 'hidden',
  },
  sectionHeader: {
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: '#121214',
    borderBottomWidth: 1,
    borderBottomColor: '#1f1f22',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#c9c9ce',
    marginBottom: 8,
    paddingLeft: 12,
  },
  filterScrollView: {
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 0,
  },
  filterButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#2b2b31',
    marginRight: 8,
    minWidth: 60,
  },
  filterButtonActive: {
    backgroundColor: '#0084ff',
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9aa0a6',
  },
  filterButtonTextActive: {
    color: '#fff',
  },

  listPad: { padding: 12, gap: 16 },

  cardRow: {
    flexDirection: 'column',
    width: 130,
    minHeight: 110,
    padding: 10,
    backgroundColor: '#1a1a1e',
    borderRadius: 20,
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  thumb: { width: 64, height: 64, borderRadius: 14, marginBottom: 10 },
  cardTitle: { color: '#fff', fontSize: 14, fontWeight: '700', textAlign: 'center', marginBottom: 4 },
  subtle: { color: '#c9c9ce', fontSize: 12, marginTop: 2, textAlign: 'center' },
  distance: { color: '#8e8e95', fontSize: 11, marginTop: 6, textAlign: 'center' },

  badgeFollowing: {
    backgroundColor: '#2b2b31',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'center',
    marginTop: 8,
    marginLeft: 6,
  },
  badgeText: { color: '#d7d7dd', fontSize: 10, fontWeight: '600' },

  cardCol: {
    width: '100%',
    minHeight: 100,
    gap: 6,
    padding: 8,
    backgroundColor: '#1a1a1e',
    borderRadius: 20,
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  eventTitle: { color: '#fff', fontSize: 15, fontWeight: '700', flex: 1 },
  eventDescription: { color: '#c9c9ce', fontSize: 13, lineHeight: 18, marginTop: 4 },
  eventDate: { color: '#007AFF', fontSize: 13, marginTop: 6, fontWeight: '500' },
  freeBadge: {
    backgroundColor: '#00c851',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  freeBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  priceBadge: {
    backgroundColor: '#0084ff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  priceBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  capacityInfo: {
    color: '#9aa0a6',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  placeholderImage: {
    backgroundColor: '#2b2b31',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#9aa0a6',
    fontSize: 32,
    fontWeight: 'bold',
  },

  search: {
    backgroundColor: '#1a1a1e',
    color: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    fontSize: 14,
    minWidth: 120,
    marginBottom: 12,
  },
  
  loadingText: {
    color: '#c9c9ce',
    textAlign: 'center',
    fontSize: 16,
    padding: 20,
  },
  emptyState: {
    padding: 20,
    alignItems: 'center',
  },
  emptyText: {
    color: '#c9c9ce',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 24,
  },
  placeholderImage: {
    backgroundColor: '#2b2b31',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
  },
  statCard: {
    alignItems: 'center',
    backgroundColor: '#1a1a1e',
    padding: 20,
    borderRadius: 12,
    minWidth: 100,
  },
  statNumber: {
    color: '#007AFF',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  statLabel: {
    color: '#888',
    fontSize: 14,
  },
  suggestedContainer: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  anotherButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  anotherButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  viewToggle: {
    flexDirection: 'row',
    backgroundColor: '#1a1a1e',
    borderRadius: 8,
    padding: 2,
    marginHorizontal: 0,
    marginTop: 12,
    marginBottom: 12,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
  },
  toggleButtonActive: {
    backgroundColor: '#007AFF',
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9aa0a6',
  },
  toggleButtonTextActive: {
    color: '#fff',
  },
  wallPostsList: {
    padding: 16,
    paddingBottom: 100,
  },
  postCardItem: {
    backgroundColor: '#1a1a1e',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2b2b31',
    alignSelf: 'center',
    width: '86%',
  },
  postCardBusinessName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 8,
  },
  postCardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  postCardText: {
    fontSize: 14,
    color: '#fff',
    lineHeight: 20,
    marginBottom: 12,
  },
  postCardImage: {
    width: '100%',
    height: 200,
    borderRadius: 8,
    marginTop: 12,
    marginBottom: 12,
    backgroundColor: '#2b2b31',
  },
  postCardDate: {
    fontSize: 13,
    color: '#fff',
    fontWeight: '500',
  },
  venueCardItem: {
    backgroundColor: '#1a1a1e',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2b2b31',
    alignSelf: 'center',
    width: '86%',
    alignItems: 'center',
  },
});